// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.29.3
// source: api/v1/missions/missions.proto

package missions

import (
	model "github.com/VeneLooool/missions-api/internal/pb/api/v1/model"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateMission struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateMission) Reset() {
	*x = CreateMission{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_missions_missions_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMission) ProtoMessage() {}

func (x *CreateMission) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_missions_missions_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMission.ProtoReflect.Descriptor instead.
func (*CreateMission) Descriptor() ([]byte, []int) {
	return file_api_v1_missions_missions_proto_rawDescGZIP(), []int{0}
}

type UpdateMission struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateMission) Reset() {
	*x = UpdateMission{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_missions_missions_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMission) ProtoMessage() {}

func (x *UpdateMission) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_missions_missions_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMission.ProtoReflect.Descriptor instead.
func (*UpdateMission) Descriptor() ([]byte, []int) {
	return file_api_v1_missions_missions_proto_rawDescGZIP(), []int{1}
}

type UpdateMissionStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateMissionStatus) Reset() {
	*x = UpdateMissionStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_missions_missions_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMissionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMissionStatus) ProtoMessage() {}

func (x *UpdateMissionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_missions_missions_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMissionStatus.ProtoReflect.Descriptor instead.
func (*UpdateMissionStatus) Descriptor() ([]byte, []int) {
	return file_api_v1_missions_missions_proto_rawDescGZIP(), []int{2}
}

type GetMissionByID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetMissionByID) Reset() {
	*x = GetMissionByID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_missions_missions_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMissionByID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMissionByID) ProtoMessage() {}

func (x *GetMissionByID) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_missions_missions_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMissionByID.ProtoReflect.Descriptor instead.
func (*GetMissionByID) Descriptor() ([]byte, []int) {
	return file_api_v1_missions_missions_proto_rawDescGZIP(), []int{3}
}

type GetMissionsByAuthor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetMissionsByAuthor) Reset() {
	*x = GetMissionsByAuthor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_missions_missions_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMissionsByAuthor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMissionsByAuthor) ProtoMessage() {}

func (x *GetMissionsByAuthor) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_missions_missions_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMissionsByAuthor.ProtoReflect.Descriptor instead.
func (*GetMissionsByAuthor) Descriptor() ([]byte, []int) {
	return file_api_v1_missions_missions_proto_rawDescGZIP(), []int{4}
}

type DeleteMission struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteMission) Reset() {
	*x = DeleteMission{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_missions_missions_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMission) ProtoMessage() {}

func (x *DeleteMission) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_missions_missions_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMission.ProtoReflect.Descriptor instead.
func (*DeleteMission) Descriptor() ([]byte, []int) {
	return file_api_v1_missions_missions_proto_rawDescGZIP(), []int{5}
}

type GetMissionsInStatuses struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetMissionsInStatuses) Reset() {
	*x = GetMissionsInStatuses{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_missions_missions_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMissionsInStatuses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMissionsInStatuses) ProtoMessage() {}

func (x *GetMissionsInStatuses) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_missions_missions_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMissionsInStatuses.ProtoReflect.Descriptor instead.
func (*GetMissionsInStatuses) Descriptor() ([]byte, []int) {
	return file_api_v1_missions_missions_proto_rawDescGZIP(), []int{6}
}

type CreateMission_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type      model.MissionType      `protobuf:"varint,2,opt,name=type,proto3,enum=missions_api.api.v1.model.MissionType" json:"type,omitempty"`
	Status    model.MissionStatus    `protobuf:"varint,3,opt,name=status,proto3,enum=missions_api.api.v1.model.MissionStatus" json:"status,omitempty"`
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CreatedBy string                 `protobuf:"bytes,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	FieldId   uint64                 `protobuf:"varint,6,opt,name=field_id,json=fieldId,proto3" json:"field_id,omitempty"`
	DroneId   uint64                 `protobuf:"varint,7,opt,name=drone_id,json=droneId,proto3" json:"drone_id,omitempty"`
	Plan      *model.Plan            `protobuf:"bytes,8,opt,name=plan,proto3" json:"plan,omitempty"`
}

func (x *CreateMission_Request) Reset() {
	*x = CreateMission_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_missions_missions_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMission_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMission_Request) ProtoMessage() {}

func (x *CreateMission_Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_missions_missions_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMission_Request.ProtoReflect.Descriptor instead.
func (*CreateMission_Request) Descriptor() ([]byte, []int) {
	return file_api_v1_missions_missions_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CreateMission_Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMission_Request) GetType() model.MissionType {
	if x != nil {
		return x.Type
	}
	return model.MissionType(0)
}

func (x *CreateMission_Request) GetStatus() model.MissionStatus {
	if x != nil {
		return x.Status
	}
	return model.MissionStatus(0)
}

func (x *CreateMission_Request) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *CreateMission_Request) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *CreateMission_Request) GetFieldId() uint64 {
	if x != nil {
		return x.FieldId
	}
	return 0
}

func (x *CreateMission_Request) GetDroneId() uint64 {
	if x != nil {
		return x.DroneId
	}
	return 0
}

func (x *CreateMission_Request) GetPlan() *model.Plan {
	if x != nil {
		return x.Plan
	}
	return nil
}

type CreateMission_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mission *model.Mission `protobuf:"bytes,1,opt,name=mission,proto3" json:"mission,omitempty"`
}

func (x *CreateMission_Response) Reset() {
	*x = CreateMission_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_missions_missions_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMission_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMission_Response) ProtoMessage() {}

func (x *CreateMission_Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_missions_missions_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMission_Response.ProtoReflect.Descriptor instead.
func (*CreateMission_Response) Descriptor() ([]byte, []int) {
	return file_api_v1_missions_missions_proto_rawDescGZIP(), []int{0, 1}
}

func (x *CreateMission_Response) GetMission() *model.Mission {
	if x != nil {
		return x.Mission
	}
	return nil
}

type UpdateMission_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status    model.MissionStatus    `protobuf:"varint,3,opt,name=status,proto3,enum=missions_api.api.v1.model.MissionStatus" json:"status,omitempty"`
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	UpdatedBy string                 `protobuf:"bytes,5,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	Plan      *model.Plan            `protobuf:"bytes,6,opt,name=plan,proto3" json:"plan,omitempty"`
}

func (x *UpdateMission_Request) Reset() {
	*x = UpdateMission_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_missions_missions_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMission_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMission_Request) ProtoMessage() {}

func (x *UpdateMission_Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_missions_missions_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMission_Request.ProtoReflect.Descriptor instead.
func (*UpdateMission_Request) Descriptor() ([]byte, []int) {
	return file_api_v1_missions_missions_proto_rawDescGZIP(), []int{1, 0}
}

func (x *UpdateMission_Request) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateMission_Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateMission_Request) GetStatus() model.MissionStatus {
	if x != nil {
		return x.Status
	}
	return model.MissionStatus(0)
}

func (x *UpdateMission_Request) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *UpdateMission_Request) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *UpdateMission_Request) GetPlan() *model.Plan {
	if x != nil {
		return x.Plan
	}
	return nil
}

type UpdateMission_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mission *model.Mission `protobuf:"bytes,1,opt,name=mission,proto3" json:"mission,omitempty"`
}

func (x *UpdateMission_Response) Reset() {
	*x = UpdateMission_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_missions_missions_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMission_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMission_Response) ProtoMessage() {}

func (x *UpdateMission_Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_missions_missions_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMission_Response.ProtoReflect.Descriptor instead.
func (*UpdateMission_Response) Descriptor() ([]byte, []int) {
	return file_api_v1_missions_missions_proto_rawDescGZIP(), []int{1, 1}
}

func (x *UpdateMission_Response) GetMission() *model.Mission {
	if x != nil {
		return x.Mission
	}
	return nil
}

type UpdateMissionStatus_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint64              `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status model.MissionStatus `protobuf:"varint,2,opt,name=status,proto3,enum=missions_api.api.v1.model.MissionStatus" json:"status,omitempty"`
}

func (x *UpdateMissionStatus_Request) Reset() {
	*x = UpdateMissionStatus_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_missions_missions_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMissionStatus_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMissionStatus_Request) ProtoMessage() {}

func (x *UpdateMissionStatus_Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_missions_missions_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMissionStatus_Request.ProtoReflect.Descriptor instead.
func (*UpdateMissionStatus_Request) Descriptor() ([]byte, []int) {
	return file_api_v1_missions_missions_proto_rawDescGZIP(), []int{2, 0}
}

func (x *UpdateMissionStatus_Request) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateMissionStatus_Request) GetStatus() model.MissionStatus {
	if x != nil {
		return x.Status
	}
	return model.MissionStatus(0)
}

type UpdateMissionStatus_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mission *model.Mission `protobuf:"bytes,1,opt,name=mission,proto3" json:"mission,omitempty"`
}

func (x *UpdateMissionStatus_Response) Reset() {
	*x = UpdateMissionStatus_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_missions_missions_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMissionStatus_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMissionStatus_Response) ProtoMessage() {}

func (x *UpdateMissionStatus_Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_missions_missions_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMissionStatus_Response.ProtoReflect.Descriptor instead.
func (*UpdateMissionStatus_Response) Descriptor() ([]byte, []int) {
	return file_api_v1_missions_missions_proto_rawDescGZIP(), []int{2, 1}
}

func (x *UpdateMissionStatus_Response) GetMission() *model.Mission {
	if x != nil {
		return x.Mission
	}
	return nil
}

type GetMissionByID_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetMissionByID_Request) Reset() {
	*x = GetMissionByID_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_missions_missions_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMissionByID_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMissionByID_Request) ProtoMessage() {}

func (x *GetMissionByID_Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_missions_missions_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMissionByID_Request.ProtoReflect.Descriptor instead.
func (*GetMissionByID_Request) Descriptor() ([]byte, []int) {
	return file_api_v1_missions_missions_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetMissionByID_Request) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetMissionByID_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mission *model.Mission `protobuf:"bytes,1,opt,name=mission,proto3" json:"mission,omitempty"`
}

func (x *GetMissionByID_Response) Reset() {
	*x = GetMissionByID_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_missions_missions_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMissionByID_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMissionByID_Response) ProtoMessage() {}

func (x *GetMissionByID_Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_missions_missions_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMissionByID_Response.ProtoReflect.Descriptor instead.
func (*GetMissionByID_Response) Descriptor() ([]byte, []int) {
	return file_api_v1_missions_missions_proto_rawDescGZIP(), []int{3, 1}
}

func (x *GetMissionByID_Response) GetMission() *model.Mission {
	if x != nil {
		return x.Mission
	}
	return nil
}

type GetMissionsByAuthor_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
}

func (x *GetMissionsByAuthor_Request) Reset() {
	*x = GetMissionsByAuthor_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_missions_missions_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMissionsByAuthor_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMissionsByAuthor_Request) ProtoMessage() {}

func (x *GetMissionsByAuthor_Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_missions_missions_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMissionsByAuthor_Request.ProtoReflect.Descriptor instead.
func (*GetMissionsByAuthor_Request) Descriptor() ([]byte, []int) {
	return file_api_v1_missions_missions_proto_rawDescGZIP(), []int{4, 0}
}

func (x *GetMissionsByAuthor_Request) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

type GetMissionsByAuthor_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Missions []*model.Mission `protobuf:"bytes,1,rep,name=missions,proto3" json:"missions,omitempty"`
}

func (x *GetMissionsByAuthor_Response) Reset() {
	*x = GetMissionsByAuthor_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_missions_missions_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMissionsByAuthor_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMissionsByAuthor_Response) ProtoMessage() {}

func (x *GetMissionsByAuthor_Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_missions_missions_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMissionsByAuthor_Response.ProtoReflect.Descriptor instead.
func (*GetMissionsByAuthor_Response) Descriptor() ([]byte, []int) {
	return file_api_v1_missions_missions_proto_rawDescGZIP(), []int{4, 1}
}

func (x *GetMissionsByAuthor_Response) GetMissions() []*model.Mission {
	if x != nil {
		return x.Missions
	}
	return nil
}

type DeleteMission_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteMission_Request) Reset() {
	*x = DeleteMission_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_missions_missions_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMission_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMission_Request) ProtoMessage() {}

func (x *DeleteMission_Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_missions_missions_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMission_Request.ProtoReflect.Descriptor instead.
func (*DeleteMission_Request) Descriptor() ([]byte, []int) {
	return file_api_v1_missions_missions_proto_rawDescGZIP(), []int{5, 0}
}

func (x *DeleteMission_Request) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetMissionsInStatuses_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Statuses []model.MissionStatus `protobuf:"varint,1,rep,packed,name=statuses,proto3,enum=missions_api.api.v1.model.MissionStatus" json:"statuses,omitempty"`
}

func (x *GetMissionsInStatuses_Request) Reset() {
	*x = GetMissionsInStatuses_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_missions_missions_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMissionsInStatuses_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMissionsInStatuses_Request) ProtoMessage() {}

func (x *GetMissionsInStatuses_Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_missions_missions_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMissionsInStatuses_Request.ProtoReflect.Descriptor instead.
func (*GetMissionsInStatuses_Request) Descriptor() ([]byte, []int) {
	return file_api_v1_missions_missions_proto_rawDescGZIP(), []int{6, 0}
}

func (x *GetMissionsInStatuses_Request) GetStatuses() []model.MissionStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type GetMissionsInStatuses_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Missions []*model.Mission `protobuf:"bytes,1,rep,name=missions,proto3" json:"missions,omitempty"`
}

func (x *GetMissionsInStatuses_Response) Reset() {
	*x = GetMissionsInStatuses_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_missions_missions_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMissionsInStatuses_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMissionsInStatuses_Response) ProtoMessage() {}

func (x *GetMissionsInStatuses_Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_missions_missions_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMissionsInStatuses_Response.ProtoReflect.Descriptor instead.
func (*GetMissionsInStatuses_Response) Descriptor() ([]byte, []int) {
	return file_api_v1_missions_missions_proto_rawDescGZIP(), []int{6, 1}
}

func (x *GetMissionsInStatuses_Response) GetMissions() []*model.Mission {
	if x != nil {
		return x.Missions
	}
	return nil
}

var File_api_v1_missions_missions_proto protoreflect.FileDescriptor

var file_api_v1_missions_missions_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x73, 0x2f, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x1c, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d,
	0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x76,
	0x31, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x70, 0x6c, 0x61, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xbc, 0x03, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x1a, 0xe0, 0x02, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x3a, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x26, 0x2e, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x40,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x28,
	0x2e, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x39, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x49, 0x64,
	0x12, 0x33, 0x0a, 0x04, 0x70, 0x6c, 0x61, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x52,
	0x04, 0x70, 0x6c, 0x61, 0x6e, 0x1a, 0x48, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3c, 0x0a, 0x07, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x61, 0x70,
	0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22,
	0xda, 0x02, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x1a, 0xfe, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x40, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x28, 0x2e, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x39, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x12, 0x33, 0x0a,
	0x04, 0x70, 0x6c, 0x61, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x04, 0x70, 0x6c,
	0x61, 0x6e, 0x1a, 0x48, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c,
	0x0a, 0x07, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x22, 0x2e, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x07, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xbc, 0x01, 0x0a,
	0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x1a, 0x5b, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x40, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x28, 0x2e, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x1a, 0x48, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a,
	0x07, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22,
	0x2e, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x07, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x75, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x49, 0x44, 0x1a, 0x19, 0x0a,
	0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x1a, 0x48, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x07, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2e, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x22, 0x82, 0x01, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x42, 0x79, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x1a, 0x1f, 0x0a, 0x07, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x1a, 0x4a, 0x0a, 0x08, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x08, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x2a, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x1a, 0x19, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x02, 0x69, 0x64, 0x22, 0xb4, 0x01, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x49, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x65, 0x73, 0x1a, 0x4f, 0x0a,
	0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x44, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x28, 0x2e, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x08, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x65, 0x73, 0x1a, 0x4a,
	0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x08, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x08, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x32, 0xef, 0x08, 0x0a, 0x08, 0x4d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x93, 0x01, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x33, 0x2e, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x34,
	0x2e, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x11, 0x3a, 0x01, 0x2a, 0x22,
	0x0c, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x98, 0x01,
	0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x33, 0x2e, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x34, 0x2e, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1c, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x16, 0x3a, 0x01, 0x2a, 0x1a, 0x11, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0xb1, 0x01, 0x0a, 0x13, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x39, 0x2e, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x3a, 0x2e, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x23, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1d, 0x3a,
	0x01, 0x2a, 0x1a, 0x18, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x98, 0x01, 0x0a,
	0x0e, 0x47, 0x65, 0x74, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x49, 0x44, 0x12,
	0x34, 0x2e, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x47,
	0x65, 0x74, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x49, 0x44, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x35, 0x2e, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x42,
	0x79, 0x49, 0x44, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x19, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x13, 0x12, 0x11, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0xb2, 0x01, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x79, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12,
	0x39, 0x2e, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x47,
	0x65, 0x74, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x79, 0x41, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x3a, 0x2e, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x79, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x24, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1e, 0x12, 0x1c,
	0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x73, 0x2f, 0x7b, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x7d, 0x12, 0x77, 0x0a, 0x0d,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x33, 0x2e,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x19, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x13, 0x2a, 0x11, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0xb4, 0x01, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x49, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x65, 0x73, 0x12,
	0x3b, 0x2e, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x47,
	0x65, 0x74, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x49, 0x6e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x3c, 0x2e, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x2e, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x4d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x49, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x65,
	0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x20, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x1a, 0x3a, 0x01, 0x2a, 0x22, 0x15, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x65, 0x73, 0x42, 0x41, 0x5a, 0x3f,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x56, 0x65, 0x6e, 0x65, 0x4c,
	0x6f, 0x6f, 0x6f, 0x6f, 0x6c, 0x2f, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2d, 0x61,
	0x70, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x3b, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_missions_missions_proto_rawDescOnce sync.Once
	file_api_v1_missions_missions_proto_rawDescData = file_api_v1_missions_missions_proto_rawDesc
)

func file_api_v1_missions_missions_proto_rawDescGZIP() []byte {
	file_api_v1_missions_missions_proto_rawDescOnce.Do(func() {
		file_api_v1_missions_missions_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_missions_missions_proto_rawDescData)
	})
	return file_api_v1_missions_missions_proto_rawDescData
}

var file_api_v1_missions_missions_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_api_v1_missions_missions_proto_goTypes = []any{
	(*CreateMission)(nil),                  // 0: missions_api.api.v1.missions.CreateMission
	(*UpdateMission)(nil),                  // 1: missions_api.api.v1.missions.UpdateMission
	(*UpdateMissionStatus)(nil),            // 2: missions_api.api.v1.missions.UpdateMissionStatus
	(*GetMissionByID)(nil),                 // 3: missions_api.api.v1.missions.GetMissionByID
	(*GetMissionsByAuthor)(nil),            // 4: missions_api.api.v1.missions.GetMissionsByAuthor
	(*DeleteMission)(nil),                  // 5: missions_api.api.v1.missions.DeleteMission
	(*GetMissionsInStatuses)(nil),          // 6: missions_api.api.v1.missions.GetMissionsInStatuses
	(*CreateMission_Request)(nil),          // 7: missions_api.api.v1.missions.CreateMission.Request
	(*CreateMission_Response)(nil),         // 8: missions_api.api.v1.missions.CreateMission.Response
	(*UpdateMission_Request)(nil),          // 9: missions_api.api.v1.missions.UpdateMission.Request
	(*UpdateMission_Response)(nil),         // 10: missions_api.api.v1.missions.UpdateMission.Response
	(*UpdateMissionStatus_Request)(nil),    // 11: missions_api.api.v1.missions.UpdateMissionStatus.Request
	(*UpdateMissionStatus_Response)(nil),   // 12: missions_api.api.v1.missions.UpdateMissionStatus.Response
	(*GetMissionByID_Request)(nil),         // 13: missions_api.api.v1.missions.GetMissionByID.Request
	(*GetMissionByID_Response)(nil),        // 14: missions_api.api.v1.missions.GetMissionByID.Response
	(*GetMissionsByAuthor_Request)(nil),    // 15: missions_api.api.v1.missions.GetMissionsByAuthor.Request
	(*GetMissionsByAuthor_Response)(nil),   // 16: missions_api.api.v1.missions.GetMissionsByAuthor.Response
	(*DeleteMission_Request)(nil),          // 17: missions_api.api.v1.missions.DeleteMission.Request
	(*GetMissionsInStatuses_Request)(nil),  // 18: missions_api.api.v1.missions.GetMissionsInStatuses.Request
	(*GetMissionsInStatuses_Response)(nil), // 19: missions_api.api.v1.missions.GetMissionsInStatuses.Response
	(model.MissionType)(0),                 // 20: missions_api.api.v1.model.MissionType
	(model.MissionStatus)(0),               // 21: missions_api.api.v1.model.MissionStatus
	(*timestamppb.Timestamp)(nil),          // 22: google.protobuf.Timestamp
	(*model.Plan)(nil),                     // 23: missions_api.api.v1.model.Plan
	(*model.Mission)(nil),                  // 24: missions_api.api.v1.model.Mission
	(*emptypb.Empty)(nil),                  // 25: google.protobuf.Empty
}
var file_api_v1_missions_missions_proto_depIdxs = []int32{
	20, // 0: missions_api.api.v1.missions.CreateMission.Request.type:type_name -> missions_api.api.v1.model.MissionType
	21, // 1: missions_api.api.v1.missions.CreateMission.Request.status:type_name -> missions_api.api.v1.model.MissionStatus
	22, // 2: missions_api.api.v1.missions.CreateMission.Request.started_at:type_name -> google.protobuf.Timestamp
	23, // 3: missions_api.api.v1.missions.CreateMission.Request.plan:type_name -> missions_api.api.v1.model.Plan
	24, // 4: missions_api.api.v1.missions.CreateMission.Response.mission:type_name -> missions_api.api.v1.model.Mission
	21, // 5: missions_api.api.v1.missions.UpdateMission.Request.status:type_name -> missions_api.api.v1.model.MissionStatus
	22, // 6: missions_api.api.v1.missions.UpdateMission.Request.started_at:type_name -> google.protobuf.Timestamp
	23, // 7: missions_api.api.v1.missions.UpdateMission.Request.plan:type_name -> missions_api.api.v1.model.Plan
	24, // 8: missions_api.api.v1.missions.UpdateMission.Response.mission:type_name -> missions_api.api.v1.model.Mission
	21, // 9: missions_api.api.v1.missions.UpdateMissionStatus.Request.status:type_name -> missions_api.api.v1.model.MissionStatus
	24, // 10: missions_api.api.v1.missions.UpdateMissionStatus.Response.mission:type_name -> missions_api.api.v1.model.Mission
	24, // 11: missions_api.api.v1.missions.GetMissionByID.Response.mission:type_name -> missions_api.api.v1.model.Mission
	24, // 12: missions_api.api.v1.missions.GetMissionsByAuthor.Response.missions:type_name -> missions_api.api.v1.model.Mission
	21, // 13: missions_api.api.v1.missions.GetMissionsInStatuses.Request.statuses:type_name -> missions_api.api.v1.model.MissionStatus
	24, // 14: missions_api.api.v1.missions.GetMissionsInStatuses.Response.missions:type_name -> missions_api.api.v1.model.Mission
	7,  // 15: missions_api.api.v1.missions.Missions.CreateMission:input_type -> missions_api.api.v1.missions.CreateMission.Request
	9,  // 16: missions_api.api.v1.missions.Missions.UpdateMission:input_type -> missions_api.api.v1.missions.UpdateMission.Request
	11, // 17: missions_api.api.v1.missions.Missions.UpdateMissionStatus:input_type -> missions_api.api.v1.missions.UpdateMissionStatus.Request
	13, // 18: missions_api.api.v1.missions.Missions.GetMissionByID:input_type -> missions_api.api.v1.missions.GetMissionByID.Request
	15, // 19: missions_api.api.v1.missions.Missions.GetMissionsByAuthor:input_type -> missions_api.api.v1.missions.GetMissionsByAuthor.Request
	17, // 20: missions_api.api.v1.missions.Missions.DeleteMission:input_type -> missions_api.api.v1.missions.DeleteMission.Request
	18, // 21: missions_api.api.v1.missions.Missions.GetMissionsInStatuses:input_type -> missions_api.api.v1.missions.GetMissionsInStatuses.Request
	8,  // 22: missions_api.api.v1.missions.Missions.CreateMission:output_type -> missions_api.api.v1.missions.CreateMission.Response
	10, // 23: missions_api.api.v1.missions.Missions.UpdateMission:output_type -> missions_api.api.v1.missions.UpdateMission.Response
	12, // 24: missions_api.api.v1.missions.Missions.UpdateMissionStatus:output_type -> missions_api.api.v1.missions.UpdateMissionStatus.Response
	14, // 25: missions_api.api.v1.missions.Missions.GetMissionByID:output_type -> missions_api.api.v1.missions.GetMissionByID.Response
	16, // 26: missions_api.api.v1.missions.Missions.GetMissionsByAuthor:output_type -> missions_api.api.v1.missions.GetMissionsByAuthor.Response
	25, // 27: missions_api.api.v1.missions.Missions.DeleteMission:output_type -> google.protobuf.Empty
	19, // 28: missions_api.api.v1.missions.Missions.GetMissionsInStatuses:output_type -> missions_api.api.v1.missions.GetMissionsInStatuses.Response
	22, // [22:29] is the sub-list for method output_type
	15, // [15:22] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_api_v1_missions_missions_proto_init() }
func file_api_v1_missions_missions_proto_init() {
	if File_api_v1_missions_missions_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_missions_missions_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CreateMission); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_missions_missions_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateMission); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_missions_missions_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateMissionStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_missions_missions_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetMissionByID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_missions_missions_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetMissionsByAuthor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_missions_missions_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteMission); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_missions_missions_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetMissionsInStatuses); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_missions_missions_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*CreateMission_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_missions_missions_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*CreateMission_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_missions_missions_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateMission_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_missions_missions_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateMission_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_missions_missions_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateMissionStatus_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_missions_missions_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateMissionStatus_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_missions_missions_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*GetMissionByID_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_missions_missions_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*GetMissionByID_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_missions_missions_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*GetMissionsByAuthor_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_missions_missions_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*GetMissionsByAuthor_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_missions_missions_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteMission_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_missions_missions_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*GetMissionsInStatuses_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_missions_missions_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*GetMissionsInStatuses_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_missions_missions_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_missions_missions_proto_goTypes,
		DependencyIndexes: file_api_v1_missions_missions_proto_depIdxs,
		MessageInfos:      file_api_v1_missions_missions_proto_msgTypes,
	}.Build()
	File_api_v1_missions_missions_proto = out.File
	file_api_v1_missions_missions_proto_rawDesc = nil
	file_api_v1_missions_missions_proto_goTypes = nil
	file_api_v1_missions_missions_proto_depIdxs = nil
}
