// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.29.3
// source: api/v1/planner/planner.proto

package planner

import (
	model "github.com/VeneLooool/missions-api/internal/pb/api/v1/model"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalculateMissionPlan struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CalculateMissionPlan) Reset() {
	*x = CalculateMissionPlan{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_planner_planner_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculateMissionPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateMissionPlan) ProtoMessage() {}

func (x *CalculateMissionPlan) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_planner_planner_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateMissionPlan.ProtoReflect.Descriptor instead.
func (*CalculateMissionPlan) Descriptor() ([]byte, []int) {
	return file_api_v1_planner_planner_proto_rawDescGZIP(), []int{0}
}

type GetMissionPlanByMissionID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetMissionPlanByMissionID) Reset() {
	*x = GetMissionPlanByMissionID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_planner_planner_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMissionPlanByMissionID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMissionPlanByMissionID) ProtoMessage() {}

func (x *GetMissionPlanByMissionID) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_planner_planner_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMissionPlanByMissionID.ProtoReflect.Descriptor instead.
func (*GetMissionPlanByMissionID) Descriptor() ([]byte, []int) {
	return file_api_v1_planner_planner_proto_rawDescGZIP(), []int{1}
}

type CalculateMissionPlan_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MissionBorders []*model.Coordinate `protobuf:"bytes,1,rep,name=mission_borders,json=missionBorders,proto3" json:"mission_borders,omitempty"`
	Type           model.MissionType   `protobuf:"varint,2,opt,name=type,proto3,enum=missions_api.api.v1.model.MissionType" json:"type,omitempty"`
}

func (x *CalculateMissionPlan_Request) Reset() {
	*x = CalculateMissionPlan_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_planner_planner_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculateMissionPlan_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateMissionPlan_Request) ProtoMessage() {}

func (x *CalculateMissionPlan_Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_planner_planner_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateMissionPlan_Request.ProtoReflect.Descriptor instead.
func (*CalculateMissionPlan_Request) Descriptor() ([]byte, []int) {
	return file_api_v1_planner_planner_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CalculateMissionPlan_Request) GetMissionBorders() []*model.Coordinate {
	if x != nil {
		return x.MissionBorders
	}
	return nil
}

func (x *CalculateMissionPlan_Request) GetType() model.MissionType {
	if x != nil {
		return x.Type
	}
	return model.MissionType(0)
}

type CalculateMissionPlan_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plan *model.Plan `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
}

func (x *CalculateMissionPlan_Response) Reset() {
	*x = CalculateMissionPlan_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_planner_planner_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculateMissionPlan_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateMissionPlan_Response) ProtoMessage() {}

func (x *CalculateMissionPlan_Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_planner_planner_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateMissionPlan_Response.ProtoReflect.Descriptor instead.
func (*CalculateMissionPlan_Response) Descriptor() ([]byte, []int) {
	return file_api_v1_planner_planner_proto_rawDescGZIP(), []int{0, 1}
}

func (x *CalculateMissionPlan_Response) GetPlan() *model.Plan {
	if x != nil {
		return x.Plan
	}
	return nil
}

type GetMissionPlanByMissionID_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MissionId uint64 `protobuf:"varint,1,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
}

func (x *GetMissionPlanByMissionID_Request) Reset() {
	*x = GetMissionPlanByMissionID_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_planner_planner_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMissionPlanByMissionID_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMissionPlanByMissionID_Request) ProtoMessage() {}

func (x *GetMissionPlanByMissionID_Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_planner_planner_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMissionPlanByMissionID_Request.ProtoReflect.Descriptor instead.
func (*GetMissionPlanByMissionID_Request) Descriptor() ([]byte, []int) {
	return file_api_v1_planner_planner_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetMissionPlanByMissionID_Request) GetMissionId() uint64 {
	if x != nil {
		return x.MissionId
	}
	return 0
}

type GetMissionPlanByMissionID_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plan *model.Plan `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
}

func (x *GetMissionPlanByMissionID_Response) Reset() {
	*x = GetMissionPlanByMissionID_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_planner_planner_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMissionPlanByMissionID_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMissionPlanByMissionID_Response) ProtoMessage() {}

func (x *GetMissionPlanByMissionID_Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_planner_planner_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMissionPlanByMissionID_Response.ProtoReflect.Descriptor instead.
func (*GetMissionPlanByMissionID_Response) Descriptor() ([]byte, []int) {
	return file_api_v1_planner_planner_proto_rawDescGZIP(), []int{1, 1}
}

func (x *GetMissionPlanByMissionID_Response) GetPlan() *model.Plan {
	if x != nil {
		return x.Plan
	}
	return nil
}

var File_api_v1_planner_planner_proto protoreflect.FileDescriptor

var file_api_v1_planner_planner_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6c, 0x61, 0x6e, 0x6e, 0x65, 0x72,
	0x2f, 0x70, 0x6c, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1b,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x2e, 0x70, 0x6c, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x1a, 0x1c, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x76,
	0x31, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x70, 0x6c, 0x61, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xef, 0x01, 0x0a, 0x14, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x4d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x50, 0x6c, 0x61, 0x6e, 0x1a, 0x95, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x4e, 0x0a, 0x0f, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f,
	0x62, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69,
	0x6e, 0x61, 0x74, 0x65, 0x52, 0x0e, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x73, 0x12, 0x3a, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x26, 0x2e, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x61, 0x70,
	0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x1a, 0x3f, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x04,
	0x70, 0x6c, 0x61, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x04, 0x70, 0x6c, 0x61,
	0x6e, 0x22, 0x86, 0x01, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x50, 0x6c, 0x61, 0x6e, 0x42, 0x79, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x1a,
	0x28, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x1a, 0x3f, 0x0a, 0x08, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x04, 0x70, 0x6c, 0x61, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x61,
	0x70, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e,
	0x50, 0x6c, 0x61, 0x6e, 0x52, 0x04, 0x70, 0x6c, 0x61, 0x6e, 0x32, 0x83, 0x03, 0x0a, 0x07, 0x50,
	0x6c, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0xad, 0x01, 0x0a, 0x14, 0x43, 0x61, 0x6c, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x65, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x6c, 0x61, 0x6e, 0x12,
	0x39, 0x2e, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x6c, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x43, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x6c,
	0x61, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x3a, 0x2e, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x70, 0x6c, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61,
	0x74, 0x65, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x6c, 0x61, 0x6e, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x3a, 0x01,
	0x2a, 0x22, 0x13, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6c, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2f, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0xc7, 0x01, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x4d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x6c, 0x61, 0x6e, 0x42, 0x79, 0x4d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x49, 0x44, 0x12, 0x3e, 0x2e, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x6c, 0x61, 0x6e, 0x6e,
	0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x6c, 0x61,
	0x6e, 0x42, 0x79, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x3f, 0x2e, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x6c, 0x61, 0x6e, 0x6e,
	0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x6c, 0x61,
	0x6e, 0x42, 0x79, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x29, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x23, 0x12, 0x21, 0x2f,
	0x76, 0x31, 0x2f, 0x70, 0x6c, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2f, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x2f, 0x7b, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x7d,
	0x42, 0x3f, 0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x56,
	0x65, 0x6e, 0x65, 0x4c, 0x6f, 0x6f, 0x6f, 0x6f, 0x6c, 0x2f, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76,
	0x31, 0x2f, 0x70, 0x6c, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x3b, 0x70, 0x6c, 0x61, 0x6e, 0x6e, 0x65,
	0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_planner_planner_proto_rawDescOnce sync.Once
	file_api_v1_planner_planner_proto_rawDescData = file_api_v1_planner_planner_proto_rawDesc
)

func file_api_v1_planner_planner_proto_rawDescGZIP() []byte {
	file_api_v1_planner_planner_proto_rawDescOnce.Do(func() {
		file_api_v1_planner_planner_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_planner_planner_proto_rawDescData)
	})
	return file_api_v1_planner_planner_proto_rawDescData
}

var file_api_v1_planner_planner_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_v1_planner_planner_proto_goTypes = []any{
	(*CalculateMissionPlan)(nil),               // 0: missions_api.api.v1.planner.CalculateMissionPlan
	(*GetMissionPlanByMissionID)(nil),          // 1: missions_api.api.v1.planner.GetMissionPlanByMissionID
	(*CalculateMissionPlan_Request)(nil),       // 2: missions_api.api.v1.planner.CalculateMissionPlan.Request
	(*CalculateMissionPlan_Response)(nil),      // 3: missions_api.api.v1.planner.CalculateMissionPlan.Response
	(*GetMissionPlanByMissionID_Request)(nil),  // 4: missions_api.api.v1.planner.GetMissionPlanByMissionID.Request
	(*GetMissionPlanByMissionID_Response)(nil), // 5: missions_api.api.v1.planner.GetMissionPlanByMissionID.Response
	(*model.Coordinate)(nil),                   // 6: missions_api.api.v1.model.Coordinate
	(model.MissionType)(0),                     // 7: missions_api.api.v1.model.MissionType
	(*model.Plan)(nil),                         // 8: missions_api.api.v1.model.Plan
}
var file_api_v1_planner_planner_proto_depIdxs = []int32{
	6, // 0: missions_api.api.v1.planner.CalculateMissionPlan.Request.mission_borders:type_name -> missions_api.api.v1.model.Coordinate
	7, // 1: missions_api.api.v1.planner.CalculateMissionPlan.Request.type:type_name -> missions_api.api.v1.model.MissionType
	8, // 2: missions_api.api.v1.planner.CalculateMissionPlan.Response.plan:type_name -> missions_api.api.v1.model.Plan
	8, // 3: missions_api.api.v1.planner.GetMissionPlanByMissionID.Response.plan:type_name -> missions_api.api.v1.model.Plan
	2, // 4: missions_api.api.v1.planner.Planner.CalculateMissionPlan:input_type -> missions_api.api.v1.planner.CalculateMissionPlan.Request
	4, // 5: missions_api.api.v1.planner.Planner.GetMissionPlanByMissionID:input_type -> missions_api.api.v1.planner.GetMissionPlanByMissionID.Request
	3, // 6: missions_api.api.v1.planner.Planner.CalculateMissionPlan:output_type -> missions_api.api.v1.planner.CalculateMissionPlan.Response
	5, // 7: missions_api.api.v1.planner.Planner.GetMissionPlanByMissionID:output_type -> missions_api.api.v1.planner.GetMissionPlanByMissionID.Response
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_v1_planner_planner_proto_init() }
func file_api_v1_planner_planner_proto_init() {
	if File_api_v1_planner_planner_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_planner_planner_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CalculateMissionPlan); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_planner_planner_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetMissionPlanByMissionID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_planner_planner_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CalculateMissionPlan_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_planner_planner_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CalculateMissionPlan_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_planner_planner_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetMissionPlanByMissionID_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_planner_planner_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetMissionPlanByMissionID_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_planner_planner_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_planner_planner_proto_goTypes,
		DependencyIndexes: file_api_v1_planner_planner_proto_depIdxs,
		MessageInfos:      file_api_v1_planner_planner_proto_msgTypes,
	}.Build()
	File_api_v1_planner_planner_proto = out.File
	file_api_v1_planner_planner_proto_rawDesc = nil
	file_api_v1_planner_planner_proto_goTypes = nil
	file_api_v1_planner_planner_proto_depIdxs = nil
}
